kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: ryanmarcus/sosd:v0
    volumes:
      - name: cache
        path: /tmp/cache
      - name: scratch
        path: /tmp/scratch
    commands:
      - ln -s /tmp/cache data
      - ln -s /tmp/cache/rmi.tar.zst rmi.tar.zst
      - ln -s /tmp/scratch rmi_data
      - scripts/download.sh
      - scripts/download_rmis.sh
      - scripts/prepare.sh
      - build/benchmark data/books_200M_uint64 data/books_200M_uint64_equality_lookups_1M
      - build/benchmark data/fb_200M_uint64 data/fb_200M_uint64_equality_lookups_1M
      - build/benchmark data/osm_cellids_200M_uint64 data/osm_cellids_200M_uint64_equality_lookups_1M
      - build/benchmark data/wiki_ts_200M_uint64 data/wiki_ts_200M_uint64_equality_lookups_1M

volumes:
  - name: cache
    host:
      path: /media/Berrik/sosd_cache
  - name: scratch
    temp: {}
